const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('meoow', {
  getBookmarks: () => ipcRenderer.invoke('browser:get-bookmarks'),
  addBookmark: (data) => ipcRenderer.invoke('browser:add-bookmark', data),
  removeBookmark: (url) => ipcRenderer.invoke('browser:remove-bookmark', url),
  getHistory: () => ipcRenderer.invoke('browser:get-history'),
  addHistory: (data) => ipcRenderer.invoke('browser:add-history', data),
  removeHistory: (url) => ipcRenderer.invoke('browser:remove-history', url),
  clearHistory: () => ipcRenderer.invoke('browser:clear-history'),
  isBookmarked: (url) => ipcRenderer.invoke('browser:is-bookmarked', url),
  search: (query) => ipcRenderer.invoke('browser:search', query),
  suggest: (query) => ipcRenderer.invoke('browser:suggest', query),
  getSettings: () => ipcRenderer.invoke('browser:get-settings'),
  setSettings: (patch) => ipcRenderer.invoke('browser:set-settings', patch),
  resetSettings: () => ipcRenderer.invoke('browser:reset-settings'),
  clearData: () => ipcRenderer.invoke('browser:clear-data'),
  getUserAgent: () => ipcRenderer.invoke('browser:get-user-agent'),
  find: (wcId, text, opts) => ipcRenderer.invoke('browser:find', wcId, text, opts),
  stopFind: (wcId) => ipcRenderer.invoke('browser:stop-find', wcId),
  onFound: (cb) => ipcRenderer.on('browser:found', (e, result) => cb(result)),
  toggleFullscreen: () => ipcRenderer.send('browser:fullscreen'),
  toggleMaximize: () => ipcRenderer.send('browser:maximize'),
  setTitle: (title) => ipcRenderer.send('browser:set-title', title),
  exitApp: () => ipcRenderer.send('browser:exit'),

  onNewTabRequest: (cb) => ipcRenderer.on('browser:new-tab', (e, url) => cb(url)),
  searchImages: (query) => ipcRenderer.invoke('browser:search-images', query),
  searchVideos: (query) => ipcRenderer.invoke('browser:search-videos', query),
  aiAsk: (prompt, opts) => ipcRenderer.invoke('browser:ai-ask', prompt, opts),
  isRisky: (url) => ipcRenderer.invoke('browser:is-risky', url),

  getAccountState: () => ipcRenderer.invoke('browser:account-state'),
  accountHealth: () => ipcRenderer.invoke('browser:account-health'),
  accountSetServer: (url) => ipcRenderer.invoke('browser:account-set-server', url),
  accountRegister: (opts) => ipcRenderer.invoke('browser:account-register', opts),
  accountLogin: (opts) => ipcRenderer.invoke('browser:account-login', opts),
  accountLogout: () => ipcRenderer.invoke('browser:account-logout'),
  profileCreate: (opts) => ipcRenderer.invoke('browser:profile-create', opts),
  profileRename: (opts) => ipcRenderer.invoke('browser:profile-rename', opts),
  profileRemove: (opts) => ipcRenderer.invoke('browser:profile-remove', opts),
  profileSwitch: (opts) => ipcRenderer.invoke('browser:profile-switch', opts),
  profileLock: (opts) => ipcRenderer.invoke('browser:profile-lock', opts),
  profileSetPin: (opts) => ipcRenderer.invoke('browser:profile-set-pin', opts),
  profileUnlock: (opts) => ipcRenderer.invoke('browser:profile-unlock', opts),

  devActiveUsers: () => ipcRenderer.invoke('browser:dev-active-users'),
  openDevWindow: () => ipcRenderer.send('browser:open-dev-window'),
});