plugins {
    id 'com.android.application'
}

android {
    namespace 'com.meoow.browser'
    compileSdk 35

    defaultConfig {
        applicationId "com.meoow.browser"
        minSdk 26
        targetSdk 35
        versionCode 10500
        versionName "1.0.5"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.11.0'
}